export const FILTER = 'FILTER';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCHED_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCHED_USERS_FAIL';
